version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  bd_kittygram:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: karkyshka/taski_backend
    env_file: .env
    volumes:
      - static:/backend_static
      # - static:/static/
      - media:/app/media/
  
  frontend:
    env_file: .env
    image: karkyshka/taski_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  
  gateway:
    image: karkyshka/taski_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/app/media/
